"""Generate contact/legal presentation from this site's home-page shell; policy article bytes stay governed."""
from pathlib import Path
import re,json,hashlib,argparse
ROOT=Path(__file__).resolve().parent.parent
config=json.loads((ROOT/'hosting/site-layout.json').read_text());brand=config['brand'];home='https://'+config['domain']+'/'
def match(pattern,text):return re.search(pattern,text,re.S).group(1)
CHECK='--check' in __import__('sys').argv
def emit(path,text):
 if CHECK:
  assert path.read_text()==text, 'generated layout drift: '+str(path)
 else:path.write_text(text)
def render():
 index=(ROOT/'index.html').read_text();head=match(r'<head>(.*?)</head>',index)
 scripts='\n'.join(re.findall(r'<script>(.*?)</script>',index,re.S));scripts='<script>'+scripts+'</script>'
 footer=match(r'(<footer\b.*?</footer>)',index)
 if brand=='bmsg':
  header=match(r'(<header\b.*?</header>)',index)
  header=re.sub(r'href="([^\"]*)"',lambda m:'href="'+(home+m[1] if m[1].startswith('#') else home+m[1] if m[1] in ['index.html','donate.html'] else m[1])+'"',header)
  section=match(r'(<section class="banner" id="connect">.*?</section>)',index)
  section=re.sub(r'<p><a[^>]*href="contact.html".*?</p>','{{FORM}}',section,flags=re.S)
  contact='<main class="contact-page">'+section+'</main>'
 else:
  intro=match(r'<main>(.*?)<span id="kindTag".*?</span>',index)+match(r'(<span id="kindTag".*?</span>)',index)
  header='<header class="product-header"><a class="product-home" href="'+home+'">'+intro+'</a><nav aria-label="Primary"><a href="'+home+'">Home</a><a href="'+home+'donate.html">Support us</a><a class="contact-link" href="contact.html">Get in touch</a></nav></header>'
  contact='<main class="contact-page"><h1>Get in touch</h1>{{FORM}}</main>'
 def wrap(title,canonical,body,extra=''):
  h=re.sub(r'<title>.*?</title>','<title>'+title+'</title>',head,flags=re.S)
  h=re.sub(r'<link rel="canonical"[^>]*>','<link rel="canonical" href="'+canonical+'">',h)
  return '<!doctype html>\n<!-- Generated by hosting/render-pages.py from index.html; do not edit this shell. -->\n<html lang="en"><head>'+h+extra+'</head><body class="site-subpage '+brand+'"><div data-environment hidden>Staging — test messages only</div>'+header+body+footer+scripts+'<script src="site-layout.js" defer></script></body></html>\n'
 form=(ROOT/'hosting/contact-form.html').read_text()
 emit(ROOT/'contact.html',wrap('Get in touch',home+'contact.html',contact.replace('{{FORM}}',form),'<link rel="stylesheet" href="contact-v1.css"><script src="contact-v1.js" defer></script>'))
 lock=json.loads((ROOT/'legal-lock.json').read_text())
 for item in lock['pages']:
  path=ROOT/item['path'];old=path.read_text();article=match(r'<article id="bmsg-legal-content">(.*?)</article>',old)
  assert hashlib.sha256(article.encode()).hexdigest()==lock['documents'][item['kind']]['sha256'],'policy source drift'
  main=match(r'<main[^>]*>(.*?)</main>',old)
  output=wrap('Privacy Policy' if item['kind']=='privacy' else 'Terms &amp; Conditions',lock['canonicalBase']+'/'+item['kind']+'.html','<main id="content" class="legal-page">'+main+'</main>','<meta name="bmsg-legal-release" content="'+lock['release']+'">')
  emit(path,output);item['sha256']=hashlib.sha256(output.encode()).hexdigest()
 emit(ROOT/'legal-lock.json',json.dumps(lock,indent=2)+'\n')
if __name__=='__main__':render()
